site_name: PocketApp Docs
site_dir: ../site
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
repo_name: PocketApp
repo_url: https://github.com/simo48hour/pocketapp
edit_uri: ''

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/simo48hour/pocketapp
      name: PocketApp GitHub

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - def_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
