export const DEV_SERVER_COMMAND = /^(?:npm run dev|pnpm (?:run )?dev|yarn (?:run )?dev|npx vite)(?:\s+[^;&|\n]+)?$/;

const INSTALL_COMMAND = /^(?:npm\s+(?:install|i|ci)|pnpm\s+install|yarn(?:\s+install)?)\b/;
const NPM_INSTALL_COMMAND = /^(npm\s+(?:install|i|ci))(?:\s+|$)(.*)$/;
const INSTALL_FLAGS = ['--prefer-offline', '--no-audit', '--no-fund'];

export type OptimizedCommand = { kind: 'shell' | 'start' | 'skip'; command?: string };

function optimizeNpmInstall(command: string) {
  const match = command.trim().match(NPM_INSTALL_COMMAND);

  if (!match) {
    return command.trim();
  }

  const args = match[2].trim();
  const missingFlags = INSTALL_FLAGS.filter((flag) => !new RegExp(`(?:^|\\s)${flag}(?:\\s|$)`).test(args));
  return [match[1], ...missingFlags, args].filter(Boolean).join(' ');
}

function isBareInstall(command: string) {
  return /^(?:npm\s+(?:install|i|ci)|pnpm\s+install|yarn(?:\s+install)?)\s*(?:--(?:prefer-offline|no-audit|no-fund|silent|yes)\s*)*$/.test(
    command.trim(),
  );
}

/**
 * Applies safe, deterministic optimizations to commands generated by the agent.
 * Package installs that add packages are preserved; only a bare install is skipped
 * when node_modules is already provisioned.
 */
export function optimizeShellCommand(
  command: string,
  options: { nodeModulesReady: boolean; devServerRunning: boolean },
): OptimizedCommand {
  const trimmed = command.trim();
  const parts = trimmed.split(/\s*&&\s*/);

  if (parts.length === 2 && INSTALL_COMMAND.test(parts[0].trim()) && DEV_SERVER_COMMAND.test(parts[1].trim())) {
    const install = parts[0].trim();
    const start = parts[1].trim();

    if (options.nodeModulesReady && isBareInstall(install)) {
      return options.devServerRunning ? { kind: 'skip' } : { kind: 'start', command: start };
    }

    return { kind: 'shell', command: `${optimizeNpmInstall(install)} && ${start}` };
  }

  if (DEV_SERVER_COMMAND.test(trimmed)) {
    return options.devServerRunning ? { kind: 'skip' } : { kind: 'start', command: trimmed };
  }

  if (INSTALL_COMMAND.test(trimmed)) {
    if (options.nodeModulesReady && isBareInstall(trimmed)) {
      return { kind: 'skip' };
    }

    return { kind: 'shell', command: optimizeNpmInstall(trimmed) };
  }

  return { kind: 'shell', command: trimmed };
}
